export const product_query = `
    query{
    products{
        data{
        id,
        attributes{
            Title,Description,Slug,Price,createdAt, 
            Image{
            data{
                attributes{
                formats
                }
            }
            }
        }
        }
    }
    }
`;
